### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by nata-pavliuk** [kevmo314/browser-geo-tz#7]
Hi, I got an error after `npm install browser-geo-tz`
`Type error: Cannot find module 'browser-geo-tz' or its corresponding type declarations`

**Comment by kevmo314** [comment]
Thanks, it looks like the type declaration file was missing. I've published a new release 0.1.1 with those types, could you update and try again?

![image](https://github.com/user-attachments/assets/5620c540-c288-4b7a-8393-59878c54713b)

**Comment by nata-pavliuk** [comment]
Thanks, let me check

**Comment by nata-pavliuk** [comment]
@kevmo314 I still have an issue. I can see the right function in code base. 
But have an issue in the browser

<img width="695" alt="Screenshot 2024-11-28 at 14 49 01" src="https://github.com/user-attachments/assets/9f33d88e-4cb2-4049-a618-268bcd8adfe5">
<img width="635" alt="Screenshot 2024-11-28 at 14 46 27" src="https://github.com/user-attachments/assets/8ec01b0b-e054-452c-a513-cf9139d8031f">
